import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AuthShowcase from "../components/AuthShowcase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <nav className="flex items-center justify-between px-6 flex-wrap">
          <h1 className="text-4xl my-9">Give Contact Card</h1>
          <div className="flex items-center gap-4 flex-wrap">
            <AuthShowcase />
            <Link className="my-6 text-white bg-gray-900 p-3 rounded-lg " href="/customize">Customize your Tweet</Link>
          </div>
        </nav>
        <section className="bg-gray-800 py-16 min-h-[80vh]">
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap items-center">
              <div className="w-full md:w-1/2">
                <h1 className="text-4xl text-gray-100 font-medium">Share your contact card <br /> with folks on Twitter!</h1>
                <p className="text-gray-500">Customize your contact card</p>
              </div>
              <div className="w-full md:w-1/2">
                <img src="https://images.pexels.com/photos/326576/pexels-photo-326576.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Hero Image" className="rounded-lg" />
              </div>
            </div>
          </div>
        </section>
        <footer>
          <p className="py-2 text-center">
            Made by <strong><a href="https://twitter.com/HarshSinghAtZ">Harsh Singh</a></strong>
          </p>
        </footer>
      </main>
    </>
  );
};

export default Home;