import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AuthShowcase from "../components/AuthShowcase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#1DA1F2] to-[#0c4364]">
        <h1 className="text-4xl my-9">Give your custom contact card on twitter by simply tagging the bot.</h1>
        <AuthShowcase/>
        <Link className="my-6 text-white bg-blue-800 p-2 rounded-md" href="/customize">Customize your tweet</Link> 
      </main>
    </>
  );
};

export default Home;